"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: px4.msg
  IDL file: SensorCombined.idl

"""

from dataclasses import dataclass
from enum import auto
from typing import TYPE_CHECKING, Optional

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
import px4

float__3 = types.typedef['px4.msg.float__3', types.array[types.float32, 3]]

@dataclass
@annotate.final
@annotate.autoid("sequential")
class SensorCombined(idl.IdlStruct, typename="px4.msg.SensorCombined"):
    timestamp: types.uint64
    gyro_rad: 'px4.msg.float__3'
    gyro_integral_dt: types.uint32
    accelerometer_timestamp_relative: types.int32
    accelerometer_m_s2: 'px4.msg.float__3'
    accelerometer_integral_dt: types.uint32
    accelerometer_clipping: types.uint8
    gyro_clipping: types.uint8
    accel_calibration_count: types.uint8
    gyro_calibration_count: types.uint8


