"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: px4.msg
  IDL file: VehicleStatus.idl

"""

from dataclasses import dataclass
from enum import auto
from typing import TYPE_CHECKING, Optional

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
import px4


@dataclass
@annotate.final
@annotate.autoid("sequential")
class VehicleStatus(idl.IdlStruct, typename="px4.msg.VehicleStatus"):
    timestamp: types.uint64
    armed_time: types.uint64
    takeoff_time: types.uint64
    arming_state: types.uint8
    latest_arming_reason: types.uint8
    latest_disarming_reason: types.uint8
    nav_state_timestamp: types.uint64
    nav_state_user_intention: types.uint8
    nav_state: types.uint8
    executor_in_charge: types.uint8
    valid_nav_states_mask: types.uint32
    can_set_nav_states_mask: types.uint32
    failure_detector_status: types.uint16
    hil_state: types.uint8
    vehicle_type: types.uint8
    failsafe: bool
    failsafe_and_user_took_over: bool
    failsafe_defer_state: types.uint8
    gcs_connection_lost: bool
    gcs_connection_lost_counter: types.uint8
    high_latency_data_link_lost: bool
    is_vtol: bool
    is_vtol_tailsitter: bool
    in_transition_mode: bool
    in_transition_to_fw: bool
    system_type: types.uint8
    system_id: types.uint8
    component_id: types.uint8
    safety_button_available: bool
    safety_off: bool
    power_input_valid: bool
    usb_connected: bool
    open_drone_id_system_present: bool
    open_drone_id_system_healthy: bool
    parachute_system_present: bool
    parachute_system_healthy: bool
    avoidance_system_required: bool
    avoidance_system_valid: bool
    rc_calibration_in_progress: bool
    calibration_enabled: bool
    pre_flight_checks_pass: bool


