"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: px4.msg.SensorCombined_Constants
  IDL file: SensorCombined.idl

"""

from dataclasses import dataclass
from enum import auto
from typing import TYPE_CHECKING, Optional

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
import px4

RELATIVE_TIMESTAMP_INVALID = 2147483647
CLIPPING_X = 1
CLIPPING_Y = 2
CLIPPING_Z = 4

